### ISSUE TITLE
what's the purpose of using the mask?

### ISSUE THREAD

**Issue by shi27feng** [murdockhou/lightweight_openpose#10]
Hi,
we are training the model with COCO dataset, and we found that your code implemented with masks:
```
mask = labels[..., params['num_kps'] + params['paf']:]
mask = tf.reshape(mask, [-1, params['height']//params['scale'], params['width']//params['scale'], 1])
```
May I ask why you need the masks here?
Thank you for your time and looking forward to reading your reply.

**Comment by murdockhou** [comment]
Hi, this is a training choose. You can set the mask to make the network
focuse on where the `labeled person` is, and the mask can make your network
converge easier. Basically, you can remove that mask and network will also
converge but may need more time.


Feng Shi <notifications@github.com> 于2019年7月13日周六 上午6:16写道：

**Comment by shi27feng** [comment]
Thanks, the reply is quite helpful.
