### ISSUE TITLE
one code question about get_paf.py

### ISSUE THREAD

**Issue by Qusever** [murdockhou/lightweight_openpose#11]
Hello, bro!
I read the get_paf.py, i have a question in the 99-line:
` mask = np.logical_or.reduce((np.abs(paf_map[0, :, :]) > 0, np.abs(paf_map[0, :, :]) > 0))`
Maybe I think
` mask = np.logical_or.reduce((np.abs(paf_map[0, :, :]) > 0, np.abs(paf_map[1, :, :]) > 0))`
is better.
If I was wrong, please tell me how to understand? Thank you!!!

**Comment by murdockhou** [comment]
@Qusever hello, thanks for your advice, in general, we need to calculate which point is valid in  x-axis or y-axis, your advice is the right way, maybe i write this error but it has very little effect on network result so i did not realize this problem. Thanks for pointing that.
