### ISSUE TITLE
NMS code for inference

### ISSUE THREAD

**Issue by Jupiter-Zhu** [murdockhou/lightweight_openpose#14]
Hi. I am wondering how do you generate paf and heatmap in test/inference time. That is, when your model generate out the heatmap, do you use any kind of non-maximum suppression, as mentioned in the paper, to generate the coordinates of the joints?  If so could you kindly point out where are they in the tf 2.0 version of the code?

**Comment by murdockhou** [comment]
Hi, i'm not implementation `test process` in tf 2.0 version, but i think it's equal with tf 1.x version. You can find the decode code in `src/pose_decode.py` and nms func in [here](https://github.com/murdockhou/lightweight_openpose/blob/master/src/pose_decode.py#L37)
