### ISSUE TITLE
Question regarding the model structure

### ISSUE THREAD

**Issue by terryzhangthu** [murdockhou/lightweight_openpose#15]
hello Murdock:

For the refinement stage "Input", I noticed that you used the concation of heatmaps and pafs without the featuremap(net_cpm).
Is it a bug? or you made this change on purpose?

Thanks        
///////////////////////////////////
outs1    = tf.concat([heatmaps1, pafs1], axis=-1)
    with tf.variable_scope('RefinementStage', reuse=tf.AUTO_REUSE):
        net = RefinementStageBlock(outs1, 128, training=is_training)
//////////////////////////////////////

**Comment by murdockhou** [comment]
@terryzhangthu I have fixed in tf 2.0 branch, please checkout this [link](https://github.com/murdockhou/lightweight_openpose/blob/tf2.0_version/nets/lightweight_openpose.py#L45)
