### ISSUE TITLE
Is the test result of ai_challenger in line with your expectations?

### ISSUE THREAD

**Issue by wangdong128** [murdockhou/lightweight_openpose#2]
Dear Shiwei Hou，
I download your trained model, and run model_test.py to test the image of ai_challenger dataset. And finally I get the result as follow:
![tnduj13zn 6 u 9veem](https://user-images.githubusercontent.com/29397783/53152590-f330de00-35f0-11e9-92c1-ea52257c0877.png)
![j u4r bky avme1bclr 05s](https://user-images.githubusercontent.com/29397783/53152593-f330de00-35f0-11e9-9d9d-e38b7a7ff026.png)
![00 zproywyz4cg2h3a9qwm](https://user-images.githubusercontent.com/29397783/53152597-f3c97480-35f0-11e9-8d25-a90a84a47053.png)
![yyzejg2d 9mok83 z3j wvg](https://user-images.githubusercontent.com/29397783/53152601-f4620b00-35f0-11e9-8d88-da2f26ecd153.png)
Is the test result of ai_challenger in line with your expectations?

**Comment by murdockhou** [comment]
@wangdong128  sorry, there are some bugs in `pose_decode.py` and have fixed. No plans to test on ai_challenger. If you like, you could test by yourself. Note that this trained model provided may be not good enough. I only trianed and do not look deep on it.
best wishes.
