### ISSUE TITLE
Error when run train.py

### ISSUE THREAD

**Issue by chenxian9999** [murdockhou/lightweight_openpose#4]
when i try to run the train.py that you have updated 2019/3/18, 
i recieve error:

File ".\train.py", line 159, in main
ValueError: input_fn should return (features, labels) as a len 2 tuple.

**Comment by murdockhou** [comment]
hi, @chenxian9999 , sorry for that i forget update `dataset.py`, now i have fixed this bug and please check for it.

**Comment by chenxian9999** [comment]
Thanks, It is work fine!
