### ISSUE TITLE
fine-tuning from MobilenetV1

### ISSUE THREAD

**Issue by mostafa-saad** [murdockhou/lightweight_openpose#6]
I would like to fine-tune starting from MobilenetV1, any guidelines? 

Did u download a model from [here](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md) and directly used it?

**Comment by murdockhou** [comment]
@mostafa-saad Maybe you can just replace backbone used MobilenetV1 totally, but i did not try before, no more useful information can provide, so sorry.
