### ISSUE TITLE
is possible to support coco dataset ?

### ISSUE THREAD

**Issue by lexuszhi1990** [murdockhou/lightweight_openpose#7]
thanks

**Comment by murdockhou** [comment]
Hi, you can modify file `src/dataset.py, src/get_heatmap.py, src/get_paf.py`. In repo i used ai-challenger format, you can used coco format dataset too as well as take care of dataset input. But i did not have a plan to support this, sorry for that.

**Comment by lexuszhi1990** [comment]
sorry to bother you, I found it easy to make it. anyway, thanks

**Comment by lexuszhi1990** [comment]
@murdockhou   你好，我最近先用ai challenge的关键点数据训练一下模型，但是发现官网上面训练集好像挂掉了，验证机可以下载，能不能分享一下？ 
万分感谢！

**Comment by murdockhou** [comment]
抱歉,我这边没办法上传到云这么大的数据集

David <notifications@github.com> 于2019年7月8日周一 上午1:12写道：

**Comment by 763593298** [comment]
> sorry to bother you, I found it easy to make it. anyway, thanks

大哥，请问怎么改那三个文件来训练coco，万分感谢。
