### ISSUE TITLE
the reason to set train_config['input_scale'] to be 8

### ISSUE THREAD

**Issue by LawrenceXu13467** [murdockhou/lightweight_openpose#9]
Hi, 

May I ask why you choose to set 
```
train_config['input_scale'] = 8 
```
in "train_config.py"? Especially why 8? Thanks.

**Comment by murdockhou** [comment]
Because the network scale is 8.

Lawrence Xu <notifications@github.com> 于2019年7月4日周四 上午12:26写道：
